[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "merge-utils"
version = "0.1.0"
dependencies = [
  "metacat",
  "rucio"
]

[project.optional-dependencies]
test = ["pytest"]