output:
    name: "{dune_mc.gen_fcl_filename}__{dune.campaign}__{dune.config_file}__{core.application.name}__{core.application.version}__{merge.cfg}__{$DUNESW_VERSION}"
    namespace: "usertests"
    dir: "/pnfs/dune/scratch/users/${USER}/merge_test/triggerAna"

sites:
    streaming: True

validation:
    skip:
        unreachable: True

merging:
    target_mode: count
    target_size: 100
    equalize: False
    chunk_max: 10
    method:
        name: "lar"
        cmd: "lar -c {cfg} -n -1 {inputs} -T temp.root "
        cfg: "triggersim_triggerana_dune10kt_1x2x2.fcl"
        rename: "temp.root"
        outputs:
          - name: "{name}__{cfg}__{UUID}__tuple.root"
          - metadata: {"core.file_format": "root"}
    