# Default configuration settings for merging
# Please create your own config files instead of modifying this one directly!

[validation]
allow_missing = false
allow_duplicates = false
checked_fields = [
    "core.run_type",
    "core.file_type",
    "core.file_format",
    "core.data_tier",
    "core.data_stream",
    "core.application.name",
    "dune.campaign",
    "dune.requestid",
    "DUNE.requestid",
    "dune.config_file",         # Not checked in old merging
    "core.application.version", # Not checked in old merging
]