# Merge-Utils configuration template with most standard options
# Angle brackets indicate the expected type of each setting, and will be ignored in user configs
# See https://dune.github.io/merge-utils/configuration.html for details on the type checking

version: "1.0.1" # Specify the merge-utils package version

input:
    mode: <opt(dids, files, dataset, query)>
    inputs: []              # List of inputs
    search_dirs: <set>      # List of directories to search for metadata files
    namespace: <str>        # Default namespace for local input files without metadata
    skip: <int>             # Skip a number of input files, overridden by '--skip #'
    limit: <int>            # Limit the number of input files, overridden by '--limit #'
    tag: <str>              # Specify a tag to identify outputs, overridden by '--tag TAG'
    comment: <str>          # Add a comment to output metadata, overridden by '--comment COMMENT'
    campaign: <str>         # Alias of metadata.overrides['dune.campaign'], set by '--campaign'
    streaming: True         # Stream files from remote sites instead of making a local copy

output:
    mode: <opt(merge, validate, metadata, dids, replicas, pfns, rses)>
    local: False          # Run merging locally instead of submitting to JustIN
    name: "{core.run_type}_{dune.campaign}_{dune.config_file}_{core.application.name}"
    namespace: <str>      # Optionally specify a namespace different from the parents
    grandparents: False   # List the parents of the input files as the parents of the merged file
    tmp_dir: "{PKG}/tmp"  # Directory for generated job scripts
    out_dir: "/pnfs/dune/scratch/users/{$USER}/merge_test" # Local output directory
    batch:                # Settings for batch merging
        lifetime: <int>   # Lifetime of output files (in days)
        rse: <str>        # Save merged files to a specific RSE
    scratch:              # Settings for temporary files from 2-stage merging
        namespace: <str>  # Optionally specify a different namespace for temporary files
        lifetime: <int>   # Lifetime of temporary files (in days)
    grouping:             # Settings for how input files are grouped into the final merged files
        mode: <opt(size, count)>
        target: <float>   # Target size (in GB) or number of files"
        equalize: <bool>  # Try to equalize the size of the merged files

metadata:
    optional: <set>       # These metadata keys are optional (overrides required and conditional keys)
    consistent: <set>     # These metadata keys must be the same for all input files
    overrides: <map>      # These metadata keys will be set to the specified values

validation:
    batch_size: <int>     # Number of files to query metacat about at once
    concurrency: <int>    # Number of threads to use for checking replicas
    fast_fail: True       # Stop processing files as soon as one batch fails validation
    check_fids: True      # Make sure parent FIDs exist in MetaCat (DIDs are always checked)
    handling:             # How to handle files with errors
        default:      <opt(quit,skip,gap)>         # Default handling mode
        duplicate:    <opt(default,quit,skip,gap)> # Duplicated files
        no_metadata:  <opt(default,quit,skip,gap)> # Files without metadata
        undeclared:   <opt(default,quit,skip,gap)> # Files without a MetaCat record
        retired:      <opt(default,quit,skip,gap)> # Retired files
        invalid:      <opt(default,quit,skip,gap)> # Metadata failed validation
        no_replicas:  <opt(default,quit,skip,gap)> # Files without any replicas
        unreachable:  <opt(default,quit,skip,gap)> # Replicas exist but exceed max distance
        inconsistent: <opt(default,quit,skip,gap)> # Metadata inconsistent with other files
        already_done: <opt(include,quit,skip,gap)> # Files that have been merged in a previous job

sites:
    default: "US_FNAL-FermiGrid"          # Default site (eg for stage 2 jobs)
    max_distance: 1000.0                  # Distances range from 0 to 101
    site_distances:                       # Distance offsets for allowed merging sites
        "US_FNAL-FermiGrid": -5.0         # Increase priority
        "CERN": 0.0
    rse_distances:                        # Distances offsets for specific RSEs
        disk: 0.0                         # Disk RSEs are preferred
        tape: 100.0                       # Tape RSEs are penalized
        "DUNE_US_FNAL_DISK_STAGE": -5.0   # Increase priority 
    dcache:                               # DCache RSEs have a staging penalty for nearline files
        "FNAL_DCACHE":
            url: "root://fndcadoor.fnal.gov:1094/pnfs/fnal.gov/usr/dune/tape_backed/dunepro"
            staging: 10.0

method:
    method_name: auto             # Can be auto, a specific default method, or the path to a custom script
    cmd: <str>                    # Optionally specify merging command, eg. '{script} {cfg} {output} {inputs}'
    cfg: <str>                    # Optionally specify a config file for merging
    script: <str>                 # Optionally specify a custom merging script
    transform: <str>              # For transform jobs, specify "app_familly.app_name"
    outputs: <list(output_file)>  # List of output files produced by the merging method
    # - name: "{NAME}_merged_{UUID}.root" # Output file name template
    #   rename: "default_name.root"       # Output name as produced by the runner script
    #   metadata: <map>                   # Per-file metadata overrides
    #   tmp_metadata: <map>               # metadata for temporary files in multi-stage merges
    #   pass2: hadd                       # Alternate merge method for output files
    #   size: sum                         # File size estimate. Can be sum, avg, or an explicit value
    #   size_min: 0                       # Minimum size for output file (for error checking)
    #   checklist: <path>                 # Checklist file to verify the output file contents
    dependencies: <set>           # Optionally specify additional files required for merging
    environment:
        dunesw_version: <str>     # DUNE software version, defaults to DUNESW_VERSION env var
        dunesw_qualifier: <str>   # DUNE software qualifier, defaults to DUNE_QUALIFIER env var
        vars: <map>               # Additional environment variables to set
        image: <str>              # Apptainer image to use for batch jobs
        products: <set>           # Extra products to load in the environment
    chunks:                       # Limits on merging individual chunks
        max_count: <int>          # Maximum number of files to merge at once
        min_count: <int>          # Minimum number of files to merge at once
        max_size: <float>         # Maximum space available for merging (in GB)
